spring:
  application:
    name: OLX-AdvertiseData
  datasource:
    url: jdbc:mysql://localhost:3306/advertise_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  config:
      import:
      - configserver:http://localhost:7777
  
server:
  port: 8090
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0


  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
      
resilience4j:
  circuitbreaker:
    instances:
      TOKEN-VALIDATION-SERVICE:
        register-health-indicator: true
        automatic-transition-from-open-to-half-open-enabled: true
        failure-rate-threshold: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 5s
 
