spring:
  application:
    name: OLX-AdvertiseData
  datasource:
    url: jdbc:mysql://localhost:3306/advertise_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  
server:
  port: 8090
 
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
      
resilience4j:
  circuitbreaker:
    instances:
      TOKEN-VALIDATION-SERVICE:
        register-health-indicator: true
        automatic-transition-from-open-to-half-open-enabled: true
        failure-rate-threshold: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 5s
 
server:
  port: 8000
spring:
  application:
    name: OLX-Login
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port:
    9000
spring:
  application:
    name: OLX-MasterData
  datasource:
    url: jdbc:mysql://localhost:3306/masterdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
